fix(#165) - Add StoryBook Support for each component
1-Platform/op-components pull request #180
Opened 2021-01-05 09:18 UTC by hybridx

### Resolves #165 

# Explain the feature/fix

- Added basic config for storybook support

## Does this PR introduce a breaking change

No

## Screenshots

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] My changes generate no new warnings
- [ ] I have performed a self-review of my own code
- [ ] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [ ] Does your component follow One Platform style guidelines?
- [ ] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [ ] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [ ] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [ ] Google Chrome [Latest 2 versions]
- [ ] Mozilla Firefox [Latest 2 versions]
- [ ] Microsoft Edge [Latest 2 versions]
- [ ] Apple Safari [Latest 2 versions]
- [ ] Microsoft Internet Explorer 11

2021-03-04 08:52 UTC, gisumit approved these changes

2021-03-04 09:54 UTC, ghanlohar requested changes

2021-03-04 09:54 UTC, ghanlohar commented on packages/opc-feedback/demo/opc-feedback.stories.js
> +    title: 'Back-To-Top',
```suggestion
    title: 'Feedback',
```

2021-03-05 06:45 UTC, ghanlohar approved these changes

2021-03-05 06:46 UTC, merged