opc-menu-drawer component
1-Platform/op-components pull request #354
Opened 2021-07-26 06:39 UTC by akhilmhdh

# Closes

Closes 1331

# Explain the feature/fix

- Implemented opc-menu-drawer, one platform drawer component
- Added test for it.

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>
<img width="1439" alt="Screenshot 2021-07-26 at 11 56 51 AM" src="https://user-images.githubusercontent.com/31166322/126943805-0169158b-d1c5-46f4-be28-8d798d6a50eb.png">
</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [x] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [x] Does your component follow One Platform style guidelines?
- [x] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [x] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [ ] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [x] Google Chrome [Latest 2 versions]
- [x] Mozilla Firefox [Latest 2 versions]
- [ ] Microsoft Edge [Latest 2 versions]
- [x] Apple Safari [Latest 2 versions]
- [ ] Microsoft Internet Explorer 11

2021-07-26 16:53 UTC, ghanlohar approved these changes
LGTM

2021-07-26 18:17 UTC, akhilmhdh commented
Added better documentation...

2021-07-27 12:12 UTC, hybridx commented
@akhilmhdh can you please rebase this code

2021-07-27 14:00 UTC, akhilmhdh commented
@hybridx  Done

2021-07-28 04:47 UTC, riginoommen requested changes

2021-07-28 04:47 UTC, riginoommen commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +        ];
Indendation needs to be fixed

2021-07-28 04:47 UTC, riginoommen commented on packages/opc-menu-drawer/package.json
> +  "description": "A web component based on Lit Element for Red hat One Platform Side Drawer.",
Please update the description

2021-07-28 04:47 UTC, riginoommen commented on packages/opc-menu-drawer/demo/index.html
> +    <opc-menu-drawer headerTitle="Akhil Mohan">
Lets put a meaning full title which sets to context

2021-07-28 04:47 UTC, riginoommen commented on packages/opc-menu-drawer/demo/index.html
> +            AM
Same as above

2021-07-28 04:47 UTC, riginoommen commented on packages/opc-menu-drawer/test/opc-menu-drawer.test.ts
> +    expect(opcMenuDrawer.headerTitle).toEqual('Akhil Mohan');
Update the test cases as per the conditions mentioned above

2021-07-28 04:49 UTC, riginoommen requested changes

2021-07-28 04:49 UTC, riginoommen commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +                    title: "BUILD in SERVICES",
```suggestion
                    title: "BUILT-IN SERVICES",
```

2021-07-28 04:49 UTC, riginoommen commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +                    title: "BUILD in SERVICES",
```suggestion
                    title: "BUILT-IN SERVICES",
```

2021-07-28 04:49 UTC, riginoommen commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +                        { name: "blog", href: "#" },
```suggestion
                        { name: "Blog", href: "#" },
```

2021-07-28 04:49 UTC, riginoommen commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +                        { name: "blog", href: "#" },
```suggestion
                        { name: "Blog", href: "#" },
```

2021-07-28 05:35 UTC, akhilmhdh commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +        ];
Done

2021-07-28 05:36 UTC, akhilmhdh commented on packages/opc-menu-drawer/demo/opc-menu-drawer.stories.js
> +                    title: "BUILD in SERVICES",
Done

2021-07-28 05:36 UTC, akhilmhdh commented on packages/opc-menu-drawer/package.json
> +  "description": "A web component based on Lit Element for Red hat One Platform Side Drawer.",
Done

2021-07-29 05:00 UTC, riginoommen commented on packages/opc-menu-drawer/package.json
> +  "description": "opc-menu-drawer is a customizable drawer component webcomponent developed using Lit elements for Red Hat One Platform.",
```suggestion
  "description": "opc-menu-drawer is a customizable drawer web component which shows the menus and user profile",
```

2021-07-30 07:02 UTC, riginoommen approved these changes

2021-07-30 09:40 UTC, deshmukhmayur approved these changes

2021-07-30 12:56 UTC, hybridx approved these changes

2021-07-30 12:57 UTC, hybridx approved these changes

2021-07-30 14:52 UTC, merged