Added target="_blank" for spa and docs button in opc-feedback
1-Platform/op-components pull request #881
Opened 2024-06-07 17:12 UTC by yamalameyooooo

# Added target="_blank" for docs and spa buttons present in opc-feedback so that the docs and feedback page opens in a new tab

### 

# Explain the feature/fix

This PR allows the user to open spa and docs link in a different tab for opc-feedback

## Does this PR introduce a breaking change

No

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [ ] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [ ] Does your component follow One Platform style guidelines?
- [ ] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [ ] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [x] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [x] Google Chrome [Latest 2 versions]
- [x] Mozilla Firefox [Latest 2 versions]
- [x] Microsoft Edge [Latest 2 versions]
- [x] Apple Safari [Latest 2 versions]
- [x] Microsoft Internet Explorer 11

2024-06-07 17:29 UTC, riginoommen requested changes
Update package-lock.json also

2024-06-07 19:33 UTC, yamalameyooooo commented
@riginoommen updated package-lock too

2024-06-07 19:55 UTC, hybridx requested changes

2024-06-07 19:55 UTC, hybridx commented on packages/opc-feedback/src/opc-feedback.ts
> +                target="_blank"
@sshamsudRH This should not be a default action, add a check and pass it down from the component attribute. There might be a use-case where we what this to open in the same page.

2024-06-07 19:56 UTC, hybridx requested changes

2024-06-07 19:56 UTC, hybridx commented on packages/opc-feedback/src/opc-feedback.ts
> +                target="_blank"
Same here

2024-06-08 05:36 UTC, yamalameyooooo commented
@hybridx made the requested changes

2024-06-08 17:24 UTC, hybridx commented
This is great work @sshamsudRH, can you please update the doc as well?

2024-06-09 04:31 UTC, yamalameyooooo commented
@hybridx updated the documentation as well

2024-06-10 14:41 UTC, hybridx approved these changes

2024-06-10 14:42 UTC, hybridx commented
LGTM approved 🎉

2024-06-11 06:26 UTC, merged