Feat/(#265):- Back to top component.
1-Platform/op-components pull request #92
Opened 2020-09-21 08:20 UTC by anjneeksharma

# Closes/Fixes/Resolves

### 

# Explain the feature/fix

Back to top component it can be used in any application user can add revealAt attribute that describe when user wants to show this back to top, Its main functionality once user click on this it will scroll window to top. 
## Does this PR introduce a breaking change

No 

## Screenshots

<details>
<summary>View Screenshots</summary>

![image](https://user-images.githubusercontent.com/12980398/93745580-678a9380-fc11-11ea-90f7-ad60e6214847.png)

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] My changes generate no new warnings
- [ ] I have performed a self-review of my own code
- [ ] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [ ] Does your component follow One Platform style guidelines?
- [ ] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [ ] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [ ] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [ ] Google Chrome [Latest 2 versions]
- [ ] Mozilla Firefox [Latest 2 versions]
- [ ] Microsoft Edge [Latest 2 versions]
- [ ] Apple Safari [Latest 2 versions]
- [ ] Microsoft Internet Explorer 11

2020-09-21 08:46 UTC, hybridx approved these changes

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/.npmignore
> +_temp
demo
src
test

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/README.md
> +A standardized web component based on Lit element for Red Hat One Platform back to top
@anjneeksharma Can you use the new README structure?

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/src/opc-back-to-top.scss
> +  font-family: 'Red Hat Text', sans-serif;
```suggestion
.show {
  font-family: 'Red Hat Text', sans-serif;
```

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/src/opc-back-to-top.scss
> +}
```suggestion
  align-items: center;
}

```

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/test/opc-back-to-top.test.ts
> +});
```suggestion
});

```

2020-09-21 08:46 UTC, hybridx commented on packages/opc-back-to-top/webpack.config.js
> +};
```suggestion
};

```

2020-09-23 06:23 UTC, hybridx requested changes

2020-09-23 06:23 UTC, hybridx commented on packages/opc-back-to-top/demo/index.html
> +    <opc-back-to-top revealAt="200"></opc-back-to-top>
```suggestion
    <opc-back-to-top reveal-at="200"></opc-back-to-top>
```

2020-09-23 09:27 UTC, gisumit requested changes

2020-09-24 09:44 UTC, gisumit commented on packages/opc-back-to-top/README.md
> +<opc-back-to-top revealAt="200"></opc-back-to-top>
Can you document what this does.

2020-09-24 09:44 UTC, gisumit commented on packages/opc-back-to-top/README.md
> +<opc-back-to-top></opc-back-to-top>
Can you add more information... please check the readme of the header and footer component to take reference.

2020-09-24 09:44 UTC, gisumit commented on packages/opc-back-to-top/README.md
> +<opc-back-to-top></opc-back-to-top>
documentation is missing on the usage in angular and react.

2020-09-24 09:44 UTC, gisumit commented on packages/opc-back-to-top/package.json
> +  "version": "0.0.1",
can you add the prerelease tag. to version.

2020-09-28 09:19 UTC, anjneeksharma commented
Closing because created on upstream.

2020-09-28 09:19 UTC, closed without merging